### ISSUE TITLE
After 5 hours of download download speed is inconsistent

### ISSUE THREAD

**Issue by Dokman** [alzamer2/Crunchyroll-XML-Decoder#4]
![image](https://cloud.githubusercontent.com/assets/2290904/25267814/9796315c-2676-11e7-9268-7d83474a50e5.png)

It will have to be at ~980 Kb/s i have 10 mb of speed.

**Comment by alzamer2** [comment]
did you increase the number of connection?
the default is 1 connection
you can do that you can do that by going to setting (by pressing 7) then press 8 to change the number of download connection 
try out 8 connection , dont think it will overload your system that way

 i fixed the code to to show kb/s rather than kbps

**Comment by Dokman** [comment]
i've been setted to 8 yesterday

**Comment by alzamer2** [comment]
is there someone that share the internet with you
if that person  is torrenting that mean he is stealing all the speed as the connection of the torrent can reach 100 

if that so try to tell him to limit the speed or you can download when he is not online

**Comment by Dokman** [comment]
i will have to see if anyone has entered into my router so...
i will see it at the evening

**Comment by alzamer2** [comment]
is there any thing new or this issue is closed?

**Comment by alzamer2** [comment]
ok i will close this issue in 24hr if there is no new

if there is new info for this issue you can re-open it again
